export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM =  'CART_REMOVE_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS ='CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD ='CART_SAVE_PAYMENT_METHOD'
<<<<<<< HEAD
export const CART_RESET_ITEM =  'CART_RESET_ITEM'
=======
export const CART_ITEM_RESET=  'CART_ITEM_RESET'
>>>>>>> 00490559a277ba562dc1d677cd8b9144f58767ae
